# Generated by Django 5.0.1 on 2024-01-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
