# Generated by Django 5.0.1 on 2024-01-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_rename_user_receipe_user_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_view_count',
        ),
    ]
