# Generated by Django 5.0.1 on 2024-01-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
