# Generated by Django 5.0.1 on 2024-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_generation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
