# Generated by Django 5.0.1 on 2024-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
